# -*- coding: utf-8 -*-
"""Activity Lab-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BlaBvRoCH0O9yPoXKzq1cu-Vg2tux1V7
"""

print("Devanga Jyoti Goswami")
print(23010012)

a=int(input("Enter any number "))
b=int(input("Enter any number "))
print(a+b)
print(a-b)
print(a*b)
print(a/b)

Length= int(input("Enter any number "))
Breadth=int(input("enter any number "))
Area=Length*Breadth
print("Area of the rectangle is equal to",Area )

Num = int(input("Enter any number "))
if (Num%2)==0:
  print("The number is even")
else:
  print("The number is odd")

Cel = int(input("Enter Temperature in celsius: "))
Faren= (Cel*9/5)+32
print("The temperature in Farenheit is",Faren)

n = int(input("Enter a positive integer (n): "))
if n < 1:
    print("Please enter a positive integer.")
else:
    result = sum_of_n_numbers_loop(n)
    print(f"The sum of the first {n} natural numbers is: {result}")

for i in range(10):
   print("9*",i,"=",i*9)

def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

num = int(input("Enter a number: "))

if num < 0:
    print("Factorial is not defined for negative numbers.")
else:
    result = factorial(num)
    print(f"The factorial of {num} is {result}")

Weight = int(input("Enter the weight in kg: "))
Height= int(input("Enter the height in m: "))
BMI = (Weight)/(Height*Height)
print("BMI of the person is",BMI)

Princ = int(input("Enter amount "))
Rate= int(input("Enter rate "))
Time=int(input("Enter time "))
Interest = (Princ*Rate*Time)/100
print("The Simple Interest is ",Interest)